WIP: bloom filters
Krukov/cashews pull request #28
Opened 2022-02-05 20:30 UTC by Krukov

2022-02-07 17:51 UTC, unmade commented on cashews/utils/bitarray.py
> +    def get(self, index: int, size: int = 1) -> int:
Seems like this method can re-written using bit-wise operator. 

Basically this method will do almost the same:
```python
def get(value, idx, size):
    return value << size & (idx + 1)
```

2022-02-07 18:25 UTC, unmade requested changes

2022-02-07 18:25 UTC, unmade commented on cashews/utils/bitarray.py
> +    def get(self, index: int, size: int = 1) -> int:
It seems like the whole method can be done using bitwise operations. It should be faster and easier to understand

```python
def get(value, idx, size):
    res = 0
    for i in range(idx, idx + size):
        res <<= 1
        if value & (2 ** i):
            res |= 1
    return res
```

2022-02-07 18:25 UTC, unmade commented on tests/test_utils.py
> +    assert b.get(0, 2) == 2
it should equal to `1`, since we sliced from the end and took only two bits (in that case - `0` and `1`)

2022-02-10 13:03 UTC, Krukov commented on cashews/utils/split_hash.py
> +    for _hash in _split_string_for_chunks(str_hash, k):
remake with bit operations

2022-03-13 19:06 UTC, merged